name: fcoregen
description: Fcore Gen Project
version: 1.0.1
homepage: https://tech.fighttech.vn/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: 2.0.0
  image: ^3.0.2
  meta: ^1.3.0
  path: ^1.8.0
  xml: ^5.1.2
  yaml: ^3.1.0
  universal_io: ^2.0.4
  http: ^0.13.3
  csv: ^5.0.0

dev_dependencies:
  flutter_lints: ^1.0.3
  test: any
