part of 'internationalization.dart';

// ignore_for_file: prefer_single_quotes, lines_longer_than_80_chars
const langRU =	{
	"hello": "Привет",
	"common.friend": "Друг",
	"common.edit": "Редактировать",
	"common.download": "Скачать",
	"common.share": "доля",
	"common.save": "Сохранить",
	"common.saved": "Спасенный",
	"common.somethingWrong": "Что-то пошло не так!",
	"common.selectVideo": "Выберите видео",
	"common.report": "Отчет",
	"common.yes": "да",
	"common.no": "Нет",
	"common.ok": "ОК",
	"common.done": "Сделанный",
	"common.cancel": "Отмена",
	"common.cancel2": "Отмена",
	"common.delete": "Удалить",
	"common.message": "Сообщение",
	"common.on": "На",
	"common.off": "Выключенный",
	"common.leave": "Покинуть",
	"common.next": "Следующий",
	"common.skip": "Пропускать",
	"common.woman": "Женщина",
	"common.man": "мужчина",
	"common.custom": "Обычай",
	"common.admin": "Админ",
	"common.search": "Поиск",
	"common.posts": "Посты",
	"common.follow": "Следовать",
	"common.followers": "Подписчики",
	"common.seeMore": "Узнать больше",
	"common.dataNotFound": "Не нашли данные!",
	"common.countinue": "Контур",
	"common.loading": "Загрузка ...",
	"common.hour": "Час",
	"common.minute": "Минута",
	"common.bottombar.home": "Дом",
	"common.confirm": "Подтверждать",
	"common.close": "Закрывать",
	"common.vip": "\rВагон",
	"common.correct": "Верный",
	"common.wrong": "Неправильный",
	"common.did": "Сделал",
	"common.send": "послать",
	"common.bottombar.statistics": "Статистика",
	"common.bottombar.notification": "Уведомление",
	"common.bottombar.competition": "Соревнование",
	"common.bottombar.profile": "Профиль",
	"common.week": "Неделя",
	"common.month": "Месяц",
	"common.year": "Год",
	"common.month_1": "Январь",
	"common.month_2": "Февраль",
	"common.month_3": "маршировать",
	"common.month_4": "апреля",
	"common.month_5": "Может",
	"common.month_6": "июнь",
	"common.month_7": "июль",
	"common.month_8": "август",
	"common.month_9": "сентябрь",
	"common.month_10": "Октябрь",
	"common.month_11": "Ноябрь",
	"common.month_12": "Декабрь",
	"DialogExit.title": "Выход",
	"DialogExit.desc": "Вы уверены, что хотите выйти?",
	"GradeSelection.title": "Выберите класс",
	"GradeSelection.listGrade": "Список оценок",
	"Dashboard.comingSoon": "Строительство здания, пожалуйста, вернитесь позже",
	"HomePage.grade": "Оценки",
	"HomePage.feedbackTitle": "Ваша оценка",
	"HomePage.feedbackDesc": "Было бы здорово получить ваш обзор для улучшения качества продукта!",
	"editProfile.title": "Информационная учетная запись",
	"ExamSelection.times": "% s раз",
	"ExamQuestion.seeMore": "Узнать больше...",
	"ExamQuestion.questionOther": "Отдых% s /% s",
	"Login.loginWithApple": "Войти с Apple ID",
	"Login.loginWithFacebook": "Войти с Facebook",
	"Login.loginWithEmail": "Войти с электронной почтой",
	"Login.loginToContinue": "Войти для продолжения",
	"Login.term1": "Войти с системой означает, что вы согласны",
	"Login.term2": "Условия эксплуатации",
	"Login.term3": "Наш",
	"Account.title": "Заголовок",
	"Account.normalUser": "Нормальный пользователь",
	"Account.proUser": "Про пользователя",
	"Account.expiryDate": "Использовать до% s",
	"Account.extension": "Расширение",
	"Account.upgrade": "Обновление",
	"Account.nickname": "Прозвище",
	"Account.dateOfBirth": "Дата рождения",
	"Account.gender": "Пол",
	"Account.phone": "Телефон",
	"Account.update": "Обновлять",
	"Account.maxLengthNickNameMsg": "Прозвище Maller Limit% D",
	"Notification.title": "Уведомление",
	"Your.title": "Для тебя",
	"Profile.title": "Счет",
	"Profile.guestTitle": "Авторизоваться",
	"Profile.guestDesc": "Чтобы получить лучший опыт и получать чрезвычайно привлекательные подарки!",
	"Profile.target": "Настройка цели",
	"Profile.exerciseDone": "Упражнение",
	"Profile.statistic": "Статистика",
	"Profile.genaralSetting": "Генаральная настройка",
	"Profile.logout": "Выйти",
	"Profile.delete": "Удалить аккаунт",
	"Profile.references": "Ввести chinhxac.vn",
	"Profile.earnMoney": "Зарабатывайте деньги",
	"Profile.giftCode": "Подарочный код",
	"Referral.title": "Код реферера",
	"Profile.rateApp": "Показатель",
	"Profile.contact": "Контакт",
	"Profile.yourReferencesCodeIs": "Код ваших ссылок составляет% s",
	"Profile.updateApp": "Обновите приложение",
	"Profile.refCode": "Код реферера Ввод",
	"Setting.title": "Параметр",
	"Setting.sound": "звук",
	"Setting.notification": "Уведомление",
	"Setting.isDark": "Темный режим",
	"Setting.deviceCode": "Код устройства",
	"Setting.deleteCache": "Удалить кэшировать",
	"Setting.tutorial": "Руководство",
	"Setting.version": "Версия% s.",
	"Setting.clearCache.succeed": "Clear Cache добиться успеха.",
	"Setting.versionLatest": "Последняя версия приложения была обновлена",
	"Setting.deleteTitle": "Удалить",
	"Setting.deleteCacheDesc": "Вы уверены, что хотите удалить данные кэширования?",
	"Setting.deleteAccountDesc": "Вы уверены, что хотите удалить аккаунт?",
	"Setting.logoutTitle": "Выход",
	"Setting.logoutDesc": "Вы действительно хотите выйти?",
	"QuestList.title": "Миссия",
	"Objective.title": "Настройка цели",
	"Objective.pleaseChoose": "Пожалуйста, выберите",
	"Objective.youCanEditInSetting": "Можете ли вы редактировать его в личных настройках приложения",
	"Objective.repeat": "Повторить",
	"Congratulations.title": "Поздравляем с получением его",
	"Congratulations.description": "Продолжайте ссылаться на \\ \"Chính xác \\\", чтобы получить больше подарков!",
	"GiftCode.title": "Обменять бонус код",
	"GiftCode.hint": "Подарочный код ввода",
	"RefCode.hint": "Код реферера",
	"topicAnalysis.title": "Анализ",
	"topicAnalysis.genaral.title": "Общая информация",
	"topicAnalysis.archivement.title": "Ваше достижение",
	"topicAnalysis.wrong.title": "Неправильный",
	"topicAnalysis.correct.title": "Верный",
	"topicAnalysis.detail.title": "Деталь",
	"topicAnalysis.question.title": "Вопрос",
	"topicAnalysis.result.title": "Результат",
	"topicAnalysis.unit.title": "Предложения",
	"topicAnalysis.view.title": "Вид",
	"statisticsPage.title": "Статистика",
	"statisticsPage.month.title": "Месяц",
	"statisticsPage.datetime.title": "Время",
	"statisticsPage.sentencesAmount.title": "Количество",
	"statisticsPage.workHour.title": "Время",
	"statisticsPage.total.title": "Общее",
	"statisticsPage.rightRate.title": "% верно",
	"statisticsPage.learnTime.title": "Продолжительность обучения",
	"statisticsPage.correctRate.title": "Правильная скорость",
	"statisticsPage.timeline.title": "ГРАФИК",
	"statisticsPage.correct.title": "коррекр",
	"membership.title": "Золотой член",
	"membership.description.prerogative": "Прерогативное членство золота",
	"membership.description.noAds": "Не содержит рекламы",
	"membership.description.bonusPoint": "Получить больше бонусных очков",
	"membership.description.support": "Расставлять приоритеты поддержки при поддержке",
	"membership.selececMembershipPackage": "Выберите Пакет членства",
	"QuestionResult.title": "Результат",
	"QuestionResult.analyzeMsg": "Невозможно проанализировать результаты, пока вы не выполнили весь вопрос"
};

          