// Copyright 2021 QSoft, Ltd. All rights reserved.

part of 'internationalization.dart';

// ignore_for_file: prefer_single_quotes, lines_longer_than_80_chars

const langJA = {
  "hello": "Xin Chào",
  "common.friend": "Bạn",
  "common.edit": "Sửa",
  "common.download": "Tải về",
  "common.share": "Chia sẻ",
  "common.save": "Lưu",
  "common.saved": "Đã lưu!",
  "common.somethingWrong": "Đã có lỗi xảy ra!",
  "common.selectVideo": "Select Video",
  "common.report": "Báo cáo",
  "common.yes": "Có",
  "common.no": "Không",
  "common.ok": "Đồng ý",
  "common.done": "Xong",
  "common.cancel": "Huỷ",
  "common.cancel2": "Huỷ bỏ",
  "common.delete": "Xoá",
  "common.message": "Tin nhắn",
  "common.on": "Mở",
  "common.off": "Tắt",
  "common.leave": "Rời khỏi",
  "common.next": "Tiếp tục",
  "common.skip": "Bỏ qua",
  "common.woman": "Nữ",
  "common.man": "Nam",
  "common.custom": "Custom",
  "common.admin": "Admin",
  "common.search": "Search",
  "common.posts": "Posts",
  "common.follow": "Follow",
  "common.followers": "Followers",
  "common.seeMore": "See More",
  "common.dataNotFound": "Not found data!",
  "common.countinue": "Tiếp tục",
  "common.loading": "Đang thực hiện...",
  "common.hour": "Giờ",
  "common.minute": "Phút",
  "common.bottombar.home": "Trang chủ",
  "common.confirm": "Xác nhận",
  "common.close": "Đóng",
  "common.vip": "VIP",
  "common.correct": "Đúng",
  "common.wrong": "Sai",
  "common.did": "Đã làm",
  "common.send": "Gửi",
  "common.bottombar.statistics": "Thống kê",
  "common.bottombar.notification": "Thông báo",
  "common.bottombar.competition": "Thi đấu",
  "common.bottombar.profile": "Cá nhân",
  "DialogExit.title": "Thoát",
  "DialogExit.desc": "Bạn có chắc muốn thoát?",
  "GradeSelection.title": "Chọn Lớp",
  "GradeSelection.listGrade": "DANH SÁCH LỚP",
  "Dashboard.comingSoon": "Chức năng đang được xây dựng, mời bạn quay lại sau",
  "HomePage.grade": "Lớp %s",
  "HomePage.feedbackTitle": "Đánh giá của bạn",
  "HomePage.feedbackDesc":
      "Sẽ thật tuyệt vời nếu nhận được đánh giá của bạn nhằm nâng cao chất lượng sản phẩm !",
  "editProfile.title": "Thông tin tài khoản",
  "ExamSelection.times": "Lần %s",
  "ExamQuestion.seeMore": "... Xem thêm",
  "ExamQuestion.questionOther": "Còn lại %s/%s",
  "Login.loginWithApple": "Đăng nhập bằng Apple ID",
  "Login.loginWithFacebook": "Đăng nhập bằng Facebook",
  "Login.loginWithEmail": "Đăng nhập bằng Email",
  "Login.loginToContinue": "Đăng nhập để tiếp tục",
  "Login.term1": "Đăng nhập hệ thống nghĩa là bạn đã đồng ý với ",
  "Login.term2": "Điều khoản sử dụng",
  "Login.term3": " của chúng tôi",
  "Account.title": "Tài khoản",
  "Account.normalUser": "Thành viên tiêu chuẩn",
  "Account.proUser": "Thành viên VIP",
  "Account.expiryDate": "Sử dụng đến %s",
  "Account.extension": "Gia hạn",
  "Account.upgrade": "Nâng cấp",
  "Account.nickname": "Nickname",
  "Account.dateOfBirth": "Ngày sinh",
  "Account.gender": "Giới tính",
  "Account.phone": "Điện thoại",
  "Account.update": "Cập nhật",
  "Account.maxLengthNickNameMsg": "Giới hạn nickname nhỏ hơn %d",
  "Notification.title": "Thông báo",
  "Your.title": "Của bạn",
  "Profile.title": "Cá Nhân",
  "Profile.guestTitle": "Đăng Nhập",
  "Profile.guestDesc":
      "Để được trải nghiệm tốt hơn và nhận được các phần quà vô cùng hấp dẫn !",
  "Profile.target": "Thiết lập mục tiêu",
  "Profile.exerciseDone": "Bài đã làm",
  "Profile.statistic": "Thống kê",
  "Profile.genaralSetting": "Cài đặt chung",
  "Profile.logout": "Đăng xuất",
  "Profile.delete": "Xoá tài khoản",
  "Profile.references": "Giới thiệu ChinhXac.Vn",
  "Profile.earnMoney": "Kiếm xu",
  "Profile.giftCode": "Đổi mã",
  "Referral.title": "Mã Người Giới Thiệu",
  "Profile.rateApp": "Đánh giá",
  "Profile.contact": "Liên hệ",
  "Profile.yourReferencesCodeIs": "Mã của bạn là %s",
  "Profile.updateApp": "Cập nhật ứng dụng",
  "Profile.refCode": "Nhập mã giới thiệu",
  "Setting.title": "Cài đặt",
  "Setting.sound": "Âm thanh",
  "Setting.notification": "Thông báo",
  "Setting.isDark": "Dark Mode",
  "Setting.deviceCode": "Mã thiết bị",
  "Setting.deleteCache": "Xoá cache",
  "Setting.tutorial": "Hướng dẫn",
  "Setting.version": "PHIÊN BẢN %s",
  "Setting.clearCache.succeed": "Đã xoá bộ nhớ tạm.",
  "Setting.versionLatest": "Phiên bản ứng dụng mới nhất đã được cập nhật",
  "Setting.deleteTitle": "Xoá",
  "Setting.deleteCacheDesc": "Bạn có chắc muốn xoá dữ liệu cache?",
  "Setting.deleteAccountDesc": "Bạn có chắc muốn xoá dữ liệu tài khoản?",
  "Setting.logoutTitle": "Thoát",
  "Setting.logoutDesc": "Bạn có chắc muốn thoát?",
  "QuestList.title": "Nhiệm Vụ",
  "Objective.title": "Thiết Lập Mục Tiêu",
  "Objective.pleaseChoose": "Thiết lập",
  "Objective.youCanEditInSetting":
      "Bạn có thể chỉnh sửa trong phần cài đặt cá nhân của ứng dụng",
  "Objective.repeat": "Lặp lại",
  "Congratulations.title": "Chúc mừng bạn đã nhận được",
  "Congratulations.description":
      "Tiếp tục giới thiệu \"Chính Xác\" để nhận thêm nhiều quà tặng khác nhé !",
  "GiftCode.title": "Đổi Mã Thưởng",
  "GiftCode.hint": "Nhập mã thưởng",
  "RefCode.hint": "Nhập mã giới thiệu",
  "topicAnalysis.title": "Phân Tích Kết Quả",
  "topicAnalysis.genaral.title": "THỐNG KÊ CHUNG",
  "topicAnalysis.archivement.title": "THÀNH TÍCH CỦA BẠN",
  "topicAnalysis.wrong.title": "Sai",
  "topicAnalysis.correct.title": "Đúng",
  "topicAnalysis.detail.title": "CHI TIẾT",
  "topicAnalysis.question.title": "Câu hỏi",
  "topicAnalysis.result.title": "Kết quả",
  "topicAnalysis.unit.title": "câu",
  "topicAnalysis.view.title": "Xem",
  "statisticsPage.title": "Thống kê",
  "statisticsPage.month.title": "Tháng",
  "statisticsPage.date.title": "Ngày",
  "statisticsPage.week.title": "Tuần",
  "statisticsPage.sentencesAmount.title": "Số Câu",
  "statisticsPage.workHour.title": "Số giờ làm",
  "statisticsPage.learnTime.title": "SỐ GIỜ LUYỆN TẬP",
  "statisticsPage.correctRate.title": "TỶ LỆ LÀM ĐÚNG BÀI",
  "statisticsPage.timeline.title": "DÒNG THỜI GIAN",
  "statisticsPage.correct.title": "đúng",
  "membership.title": "Thành viên vàng",
  "membership.description.prerogative": "Đặc Quyền Thành Viên Vàng",
  "membership.description.noAds": "Không chứa quảng cáo",
  "membership.description.bonusPoint": "Nhận nhiều điểm thưởng hơn",
  "membership.description.support": "Ưu tiên hỗ trợ khi có nhu cầu",
  "membership.selececMembershipPackage": "Chọn gói VIP",
  "QuestionResult.title": "Kết Quả",
  "QuestionResult.analyzeMsg":
      "Không thể phân tích kết quả khi bạn chưa hoàn thành toàn bộ câu hỏi",
};
