part of 'internationalization.dart';

// ignore_for_file: prefer_single_quotes, lines_longer_than_80_chars
const langIT =	{
	"hello": "Ciao",
	"common.friend": "Amico",
	"common.edit": "modificare",
	"common.download": "Scarica",
	"common.share": "Condividere",
	"common.save": "Salva",
	"common.saved": "Salvato",
	"common.somethingWrong": "Qualcosa è andato storto!",
	"common.selectVideo": "Seleziona video.",
	"common.report": "rapporto",
	"common.yes": "sì",
	"common.no": "No",
	"common.ok": "ok",
	"common.done": "Fatto",
	"common.cancel": "Annulla",
	"common.cancel2": "Annulla",
	"common.delete": "Elimina",
	"common.message": "Messaggio",
	"common.on": "Sopra",
	"common.off": "Fuori",
	"common.leave": "Partire",
	"common.next": "Il prossimo",
	"common.skip": "Salta",
	"common.woman": "Donna",
	"common.man": "Uomo",
	"common.custom": "Abitudine",
	"common.admin": "Amministratore",
	"common.search": "Ricerca",
	"common.posts": "Post",
	"common.follow": "Seguire",
	"common.followers": "Seguaci",
	"common.seeMore": "Vedi altro",
	"common.dataNotFound": "Dati non trovati!",
	"common.countinue": "In forma",
	"common.loading": "Caricamento in corso...",
	"common.hour": "Ora",
	"common.minute": "Minuto",
	"common.bottombar.home": "Casa",
	"common.confirm": "Confermare",
	"common.close": "Vicino",
	"common.vip": "\rVip.",
	"common.correct": "Corretta",
	"common.wrong": "Sbagliato",
	"common.did": "Fatto",
	"common.send": "Spedire",
	"common.bottombar.statistics": "Statistiche",
	"common.bottombar.notification": "Notifica",
	"common.bottombar.competition": "concorrenza",
	"common.bottombar.profile": "Profilo",
	"common.week": "Settimana",
	"common.month": "Mese",
	"common.year": "Anno",
	"common.month_1": "gennaio",
	"common.month_2": "febbraio",
	"common.month_3": "marzo",
	"common.month_4": "aprile",
	"common.month_5": "Maggio",
	"common.month_6": "giugno",
	"common.month_7": "luglio",
	"common.month_8": "agosto",
	"common.month_9": "settembre",
	"common.month_10": "ottobre",
	"common.month_11": "novembre",
	"common.month_12": "dicembre",
	"DialogExit.title": "Uscita",
	"DialogExit.desc": "Siete sicuri di voler uscire?",
	"GradeSelection.title": "Seleziona Grado.",
	"GradeSelection.listGrade": "Lista di lista",
	"Dashboard.comingSoon": "Costruzione di edifici, per favore torna più tardi",
	"HomePage.grade": "Gradi",
	"HomePage.feedbackTitle": "La tua valutazione",
	"HomePage.feedbackDesc": "Sarebbe bello ricevere la tua recensione per migliorare la qualità del prodotto!",
	"editProfile.title": "Account Info",
	"ExamSelection.times": "% s Times.",
	"ExamQuestion.seeMore": "Vedi altro...",
	"ExamQuestion.questionOther": "Riposo% s /% s",
	"Login.loginWithApple": "Accedi con l'ID Apple",
	"Login.loginWithFacebook": "Fai il login con facebook",
	"Login.loginWithEmail": "Accedi con e-mail",
	"Login.loginToContinue": "Accedi per continuare",
	"Login.term1": "Login con il sistema significa che accetti",
	"Login.term2": "Termini di utilizzo",
	"Login.term3": "Nostro",
	"Account.title": "Titolo",
	"Account.normalUser": "Utente normale",
	"Account.proUser": "Pro utente",
	"Account.expiryDate": "Utilizzare fino a% s",
	"Account.extension": "Estensione",
	"Account.upgrade": "Aggiornamento",
	"Account.nickname": "Soprannome",
	"Account.dateOfBirth": "Data di nascita",
	"Account.gender": "Genere",
	"Account.phone": "Telefono",
	"Account.update": "Aggiornare",
	"Account.maxLengthNickNameMsg": "MALLER NICKNAME Limit% D",
	"Notification.title": "Notifica",
	"Your.title": "Per te",
	"Profile.title": "account",
	"Profile.guestTitle": "Login",
	"Profile.guestDesc": "Avere un'esperienza migliore e ricevere regali estremamente attraenti!",
	"Profile.target": "Installazione target.",
	"Profile.exerciseDone": "Esercizio fatto",
	"Profile.statistic": "Statistica",
	"Profile.genaralSetting": "Impostazione graida",
	"Profile.logout": "Disconnettersi",
	"Profile.delete": "Eliminare l'account",
	"Profile.references": "Introdurre chinhxac.vn.",
	"Profile.earnMoney": "Guadagnare soldi",
	"Profile.giftCode": "Codice regalo",
	"Referral.title": "Codice di riferimento",
	"Profile.rateApp": "Vota",
	"Profile.contact": "Contatto",
	"Profile.yourReferencesCodeIs": "Il tuo codice riferimenti è% s",
	"Profile.updateApp": "Aggiorna App.",
	"Profile.refCode": "Codice referrer Enter.",
	"Setting.title": "Ambientazione",
	"Setting.sound": "suono",
	"Setting.notification": "Notifica",
	"Setting.isDark": "Modalità scura",
	"Setting.deviceCode": "Codice dispositivo",
	"Setting.deleteCache": "Elimina cache",
	"Setting.tutorial": "Tutorial",
	"Setting.version": "VERSIONE% S.",
	"Setting.clearCache.succeed": "La cache chiara ha successo.",
	"Setting.versionLatest": "La versione più recente è stata aggiornata",
	"Setting.deleteTitle": "Elimina",
	"Setting.deleteCacheDesc": "Sei sicuro di voler cancellare i dati della cache?",
	"Setting.deleteAccountDesc": "Sei sicuro di voler eliminare account?",
	"Setting.logoutTitle": "Uscita",
	"Setting.logoutDesc": "Sei sicuro di voler uscire?",
	"QuestList.title": "Missione",
	"Objective.title": "Installazione target.",
	"Objective.pleaseChoose": "Si prega di scegliere",
	"Objective.youCanEditInSetting": "Puoi modificarlo nelle impostazioni personali dell'app",
	"Objective.repeat": "Ripetere",
	"Congratulations.title": "Congratulazioni per averlo",
	"Congratulations.description": "Continua a riferire \\ \"chính xác \\\" per ricevere più regali!",
	"GiftCode.title": "Riscatta il codice bonus",
	"GiftCode.hint": "Invio del codice regalo",
	"RefCode.hint": "Codice di riferimento",
	"topicAnalysis.title": "Analisi",
	"topicAnalysis.genaral.title": "Statistiche generali",
	"topicAnalysis.archivement.title": "Il tuo risultato",
	"topicAnalysis.wrong.title": "Sbagliato",
	"topicAnalysis.correct.title": "Corretta",
	"topicAnalysis.detail.title": "DETTAGLIO",
	"topicAnalysis.question.title": "Domanda",
	"topicAnalysis.result.title": "Risultato",
	"topicAnalysis.unit.title": "Frasi",
	"topicAnalysis.view.title": "Visualizza",
	"statisticsPage.title": "Statistiche",
	"statisticsPage.month.title": "Mese",
	"statisticsPage.datetime.title": "Tempo",
	"statisticsPage.sentencesAmount.title": "Quantità",
	"statisticsPage.workHour.title": "Tempo",
	"statisticsPage.total.title": "Totale",
	"statisticsPage.rightRate.title": "% giusto",
	"statisticsPage.learnTime.title": "Durata dell'apprendimento",
	"statisticsPage.correctRate.title": "Corretto tasso",
	"statisticsPage.timeline.title": "SEQUENZA TEMPORALE",
	"statisticsPage.correct.title": "carentere",
	"membership.title": "Membro dell'oro",
	"membership.description.prerogative": "Prerogativa dell'armbito dell'oro",
	"membership.description.noAds": "Non contiene annunci",
	"membership.description.bonusPoint": "Ottieni più punti bonus",
	"membership.description.support": "Prioritizzare il supporto quando il supporto",
	"membership.selececMembershipPackage": "Seleziona il pacchetto di iscrizione",
	"QuestionResult.title": "Risultato",
	"QuestionResult.analyzeMsg": "Non è possibile analizzare i risultati finché non hai completato l'intera domanda"
};

          