part of 'internationalization.dart';

// ignore_for_file: prefer_single_quotes, lines_longer_than_80_chars
const langAR =	{
	"hello": "مرحبا",
	"common.friend": "صديق",
	"common.edit": "يحرر",
	"common.download": "تحميل",
	"common.share": "يشارك",
	"common.save": "يحفظ",
	"common.saved": "تم الحفظ",
	"common.somethingWrong": "هناك خطأ ما!",
	"common.selectVideo": "حدد الفيديو",
	"common.report": "تقرير",
	"common.yes": "نعم",
	"common.no": "لا",
	"common.ok": "نعم",
	"common.done": "منجز",
	"common.cancel": "يلغي",
	"common.cancel2": "يلغي",
	"common.delete": "حذف",
	"common.message": "رسالة",
	"common.on": "على",
	"common.off": "عن",
	"common.leave": "غادر",
	"common.next": "التالي",
	"common.skip": "يتخطى",
	"common.woman": "النساء",
	"common.man": "رجل",
	"common.custom": "العادة",
	"common.admin": "مشرف",
	"common.search": "يبحث",
	"common.posts": "المشاركات",
	"common.follow": "يتبع",
	"common.followers": "متابعون",
	"common.seeMore": "شاهد المزيد",
	"common.dataNotFound": "غير موجود البيانات!",
	"common.countinue": "العد",
	"common.loading": "جار التحميل...",
	"common.hour": "ساعة",
	"common.minute": "دقيقة",
	"common.bottombar.home": "منزل، بيت",
	"common.confirm": "يتأكد",
	"common.close": "يغلق",
	"common.vip": "\rكبار الشخصيات",
	"common.correct": "صيح",
	"common.wrong": "خاطئ",
	"common.did": "فعلت",
	"common.send": "إرسال",
	"common.bottombar.statistics": "إحصائيات",
	"common.bottombar.notification": "تنبيه",
	"common.bottombar.competition": "مسابقة",
	"common.bottombar.profile": "الملف الشخصي",
	"common.week": "أسبوع",
	"common.month": "الشهر",
	"common.year": "سنة",
	"common.month_1": "كانون الثاني",
	"common.month_2": "شهر فبراير",
	"common.month_3": "مارس",
	"common.month_4": "أبريل",
	"common.month_5": "مايو",
	"common.month_6": "يونيو",
	"common.month_7": "تموز",
	"common.month_8": "أغسطس",
	"common.month_9": "شهر سبتمبر",
	"common.month_10": "اكتوبر",
	"common.month_11": "شهر نوفمبر",
	"common.month_12": "ديسمبر",
	"DialogExit.title": "مخرج",
	"DialogExit.desc": "هل أنت متأكد من انك تريد الخروج؟",
	"GradeSelection.title": "حدد الصف",
	"GradeSelection.listGrade": "قائمة الصف",
	"Dashboard.comingSoon": "بناء البناء، يرجى العودة في وقت لاحق",
	"HomePage.grade": "درجات",
	"HomePage.feedbackTitle": "تقييمك",
	"HomePage.feedbackDesc": "سيكون من الرائع استلام مراجعتك لتحسين جودة المنتج!",
	"editProfile.title": "حساب المعلومات",
	"ExamSelection.times": "٪ S مرات",
	"ExamQuestion.seeMore": "شاهد المزيد...",
	"ExamQuestion.questionOther": "راحة٪ s /٪ s",
	"Login.loginWithApple": "تسجيل الدخول باستخدام معرف Apple",
	"Login.loginWithFacebook": "تسجيل الدخول باستخدام الفيسبوك",
	"Login.loginWithEmail": "تسجيل الدخول مع البريد الإلكتروني",
	"Login.loginToContinue": "تسجيل الدخول للمتابعة",
	"Login.term1": "تسجيل الدخول باستخدام النظام يعني أنك توافق على",
	"Login.term2": "تعليمات الاستخدام",
	"Login.term3": "لنا",
	"Account.title": "لقب",
	"Account.normalUser": "المستخدم العادي",
	"Account.proUser": "المحترفين للمستخدم",
	"Account.expiryDate": "استخدام ما يصل إلى٪ s",
	"Account.extension": "تمديد",
	"Account.upgrade": "رفع مستوى",
	"Account.nickname": "اسم الشهرة",
	"Account.dateOfBirth": "تاريخ الولادة",
	"Account.gender": "جنس",
	"Account.phone": "هاتف",
	"Account.update": "تحديث",
	"Account.maxLengthNickNameMsg": "الحد المسكي الأصغر الحد٪ د",
	"Notification.title": "تنبيه",
	"Your.title": "لك",
	"Profile.title": "حساب",
	"Profile.guestTitle": "تسجيل الدخول",
	"Profile.guestDesc": "للحصول على تجربة أفضل وتلقي هدايا جذابة للغاية!",
	"Profile.target": "هدف الإعداد",
	"Profile.exerciseDone": "ممارسة القيام به",
	"Profile.statistic": "الإحصائية",
	"Profile.genaralSetting": "إعداد التناسلية",
	"Profile.logout": "تسجيل خروج",
	"Profile.delete": "حذف الحساب",
	"Profile.references": "إدخال chinhxac.vn.",
	"Profile.earnMoney": "يكتسب نقود",
	"Profile.giftCode": "كود هدية",
	"Referral.title": "كود المرجع",
	"Profile.rateApp": "معدل",
	"Profile.contact": "اتصال",
	"Profile.yourReferencesCodeIs": "رمز المراجع لديك هو٪ s",
	"Profile.updateApp": "تحديث التطبيق",
	"Profile.refCode": "إظهار رمز ENTER.",
	"Setting.title": "جلسة",
	"Setting.sound": "يبدو",
	"Setting.notification": "تنبيه",
	"Setting.isDark": "الوضع المظلم",
	"Setting.deviceCode": "رمز الجهاز",
	"Setting.deleteCache": "حذف التخزين المؤقت",
	"Setting.tutorial": "درس تعليمي",
	"Setting.version": "النسخة٪ S.",
	"Setting.clearCache.succeed": "تنجح ذاكرة التخزين المؤقت واضحة.",
	"Setting.versionLatest": "تم تحديث أحدث إصدار التطبيق",
	"Setting.deleteTitle": "حذف",
	"Setting.deleteCacheDesc": "هل أنت متأكد من أنك تريد حذف بيانات ذاكرة التخزين المؤقت؟",
	"Setting.deleteAccountDesc": "هل أنت متأكد أنك تريد حذف الحساب؟",
	"Setting.logoutTitle": "مخرج",
	"Setting.logoutDesc": "هل أنت متأكد أنك تريد تسجيل الخروج؟",
	"QuestList.title": "مهمة",
	"Objective.title": "هدف الإعداد",
	"Objective.pleaseChoose": "اختر من فضلك",
	"Objective.youCanEditInSetting": "يمكنك تحريره في الإعدادات الشخصية للتطبيق",
	"Objective.repeat": "يكرر",
	"Congratulations.title": "تهانينا على الحصول عليها",
	"Congratulations.description": "استمر في الرجوع \\ \"Chính Xác \\\" للحصول على المزيد من الهدايا!",
	"GiftCode.title": "استبدال كود المكافأة",
	"GiftCode.hint": "رمز الهدية يدخل",
	"RefCode.hint": "كود المرجع",
	"topicAnalysis.title": "تحليل",
	"topicAnalysis.genaral.title": "إحصاءات عامة",
	"topicAnalysis.archivement.title": "إنجازك",
	"topicAnalysis.wrong.title": "خاطئ",
	"topicAnalysis.correct.title": "صيح",
	"topicAnalysis.detail.title": "تفاصيل",
	"topicAnalysis.question.title": "سؤال",
	"topicAnalysis.result.title": "نتيجة",
	"topicAnalysis.unit.title": "جمل",
	"topicAnalysis.view.title": "منظر",
	"statisticsPage.title": "إحصائيات",
	"statisticsPage.month.title": "الشهر",
	"statisticsPage.datetime.title": "زمن",
	"statisticsPage.sentencesAmount.title": "كمية",
	"statisticsPage.workHour.title": "زمن",
	"statisticsPage.total.title": "مجموع",
	"statisticsPage.rightRate.title": "٪ حق",
	"statisticsPage.learnTime.title": "مدة التعلم",
	"statisticsPage.correctRate.title": "معدل صحيح",
	"statisticsPage.timeline.title": "الجدول الزمني",
	"statisticsPage.correct.title": "كرر",
	"membership.title": "عضو ذهبي",
	"membership.description.prerogative": "عضوية الذهب غامضة",
	"membership.description.noAds": "لا يحتوي على إعلانات",
	"membership.description.bonusPoint": "الحصول على المزيد من نقاط المكافأة",
	"membership.description.support": "إعطاء الأولوية الدعم عند الدعم",
	"membership.selececMembershipPackage": "حدد حزمة العضوية",
	"QuestionResult.title": "نتيجة",
	"QuestionResult.analyzeMsg": "لا يمكن تحليل النتائج حتى تكمل السؤال بأكمله"
};

          